In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('Uncleaned_data1.csv').drop('Unnamed: 0',axis=1)
data.head()

,voted_for_republican,very_freq_voter,freq_voter,voted_03_05_2013,voted_05_21_2013,voted_06_07_2016,age,party,education,ismarried,home_owner,renters,ethnic,sex,hhcount
0,0,0,1,0,0,1,51.0,D,some_college,N,H,Y,white,M,1
1,0,0,0,0,0,1,53.0,D,some_college,Y,NaN,Y,white,M,1
2,1,0,0,0,0,0,59.0,R,doctorate,N,H,Y,hispanic,M,2
3,1,0,0,0,0,1,23.0,D,bachelors,N,H,N,black,M,5
4,1,1,1,1,1,1,79.0,R,HS_drop_out,N,NaN,Y,white,F,1

In [8]:
def get_dummy_function(data,column):
    if len(pd.get_dummies(data[column]).columns)==2:
        d = pd.get_dummies(data[column],prefix=str(data[column].name))
        col_drop_name = pd.get_dummies(data[column],prefix=str(data[column].name)).columns[0]
        d.drop(col_drop_name,axis=1,inplace=True)
        data.drop(column,axis=1,inplace=True)
        return pd.concat([data,d],axis=1)
    else:
        d = pd.get_dummies(data[column],prefix=str(data[column].name))
        col_drop_name = d.columns[-1]
        d.drop(col_drop_name,axis=1)
        data.drop(column,axis=1,inplace=True)
        return pd.concat([data,d],axis=1)
#data[['source','relationship_score']] = data[['source','relationship_score']].fillna(0)
for i in ['party','home_owner','sex','renters','ismarried','education','ethnic']:
    data = get_dummy_function(data,i)
data.head()

,voted_for_republican,very_freq_voter,freq_voter,voted_03_05_2013,voted_05_21_2013,voted_06_07_2016,age,hhcount,party_AI,party_D,...,education_high_school,education_masters,education_some_college,education_trade_school,ethnic_asian,ethnic_black,ethnic_hispanic,ethnic_indian,ethnic_jewish,ethnic_white
0,0,0,1,0,0,1,51.0,1,0,1,...,0,0,1,0,0,0,0,0,0,1
1,0,0,0,0,0,1,53.0,1,0,1,...,0,0,1,0,0,0,0,0,0,1
2,1,0,0,0,0,0,59.0,2,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1,0,0,0,0,1,23.0,5,0,1,...,0,0,0,0,0,1,0,0,0,0
4,1,1,1,1,1,1,79.0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

# Now drop the highly correlated features.

In [9]:
cor = data.drop('voted_for_republican',axis=1).corr()
cor.head()

,very_freq_voter,freq_voter,voted_03_05_2013,voted_05_21_2013,voted_06_07_2016,age,hhcount,party_AI,party_D,party_DS,...,education_high_school,education_masters,education_some_college,education_trade_school,ethnic_asian,ethnic_black,ethnic_hispanic,ethnic_indian,ethnic_jewish,ethnic_white
very_freq_voter,1.000000,0.637021,0.623417,0.600263,0.298347,0.400140,-0.012341,-0.055501,0.023452,-0.065548,...,-0.046170,0.055924,0.011131,-0.093350,-0.029694,0.066248,-0.082407,0.005933,0.023873,0.015069
freq_voter,0.637021,1.000000,0.561469,0.549305,0.266893,0.430570,-0.037264,-0.044543,-0.063537,-0.018769,...,-0.022381,0.072089,-0.023455,-0.110041,-0.020061,0.058599,-0.067195,0.038966,0.000381,0.009959
voted_03_05_2013,0.623417,0.561469,1.000000,0.598211,0.168721,0.478017,-0.007693,-0.055061,-0.056068,-0.041957,...,-0.026244,0.059112,-0.020058,-0.125026,-0.013942,0.071295,-0.051410,0.021696,0.040552,-0.030543
voted_05_21_2013,0.600263,0.549305,0.598211,1.000000,0.156452,0.433585,0.008709,-0.040255,-0.004243,-0.027904,...,-0.008612,0.056783,-0.009064,-0.102717,-0.028267,0.066739,-0.062376,0.025836,0.029485,-0.024928
voted_06_07_2016,0.298347,0.266893,0.168721,0.156452,1.000000,0.125770,0.018734,-0.093578,0.101632,-0.039076,...,-0.038721,-0.013677,0.008283,-0.054082,-0.023765,0.047579,-0.050866,0.024087,-0.009258,0.017672

In [10]:
highly_corellated1 = {}
threshold = 0.6
for i in cor.index:
    for j in cor.columns:
        if i!=j and np.abs(cor.loc[i][j])>threshold:
            highly_corellated1[(i,j)] = [cor.loc[i][j]]

highly_corellated = pd.DataFrame(highly_corellated1).transpose()
highly_corellated

                                          0
freq_voter       very_freq_voter   0.637021
party_D          party_R          -0.655736
party_R          party_D          -0.655736
very_freq_voter  freq_voter        0.637021
                 voted_03_05_2013  0.623417
                 voted_05_21_2013  0.600263
voted_03_05_2013 very_freq_voter   0.623417
voted_05_21_2013 very_freq_voter   0.600263

Based upon these, I'll drop very freq voter

In [11]:
data.drop(['very_freq_voter'],axis=1,inplace=True)
data.to_csv('data_dummified.csv')
data.head()

,voted_for_republican,freq_voter,voted_03_05_2013,voted_05_21_2013,voted_06_07_2016,age,hhcount,party_AI,party_D,party_DS,...,education_high_school,education_masters,education_some_college,education_trade_school,ethnic_asian,ethnic_black,ethnic_hispanic,ethnic_indian,ethnic_jewish,ethnic_white
0,0,1,0,0,1,51.0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,1
1,0,0,0,0,1,53.0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,1
2,1,0,0,0,0,59.0,2,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1,0,0,0,1,23.0,5,0,1,0,...,0,0,0,0,0,1,0,0,0,0
4,1,1,1,1,1,79.0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1

Now I'll find interaction features for the binary variables.

In [14]:
from sklearn.preprocessing import PolynomialFeatures
exclude_these = ['voted_for_republican','age','hhcount']
interaction = PolynomialFeatures(degree=2, interaction_only=True,include_bias=False)
interaction.fit_transform(data.drop(exclude_these,axis=1))
c = interaction.get_feature_names(data.drop(exclude_these,axis=1).columns)
interaction_features = pd.DataFrame(interaction.fit_transform(data.drop(exclude_these,axis=1)),columns=c)
data2 = pd.concat([data[exclude_these],interaction_features],axis=1)
print('New shape is: ',data2.shape)
data2.head()

New shape is:  (1577, 438)

,voted_for_republican,age,hhcount,freq_voter,voted_03_05_2013,voted_05_21_2013,voted_06_07_2016,party_AI,party_D,party_DS,...,ethnic_black ethnic_hispanic,ethnic_black ethnic_indian,ethnic_black ethnic_jewish,ethnic_black ethnic_white,ethnic_hispanic ethnic_indian,ethnic_hispanic ethnic_jewish,ethnic_hispanic ethnic_white,ethnic_indian ethnic_jewish,ethnic_indian ethnic_white,ethnic_jewish ethnic_white
0,0,51.0,1,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,53.0,1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,59.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,23.0,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,79.0,1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
data2.to_csv('polynomial_features.csv')

In [18]:
from scipy import stats
from sklearn.metrics import auc
import numpy as np
import warnings
warnings.filterwarnings('ignore')

def seperate_dataframe(data,column):
    converters = list(data[data['voted_for_republican']==1][column])
    non_converters = list(data[data['voted_for_republican']==0][column])
    return converters, non_converters

def permutation_mean(convert_data, non_convert_data):
    """Generate a permutation sample from two data sets."""
    # Concatenate the data sets: data
    data = np.concatenate((convert_data,non_convert_data))
    # Permute the concatenated array: permuted_data
    permuted_data = np.random.permutation(data)
    # Split the permuted array into two: perm_sample_1, perm_sample_2
    convert_permutation = permuted_data[:len(convert_data)]
    non_convert_permutation = permuted_data[len(non_convert_data):]
    #Return the permutated Mean
    return convert_permutation.mean() - non_convert_permutation.mean()

def build_normal_distribution(x,y,number_of_permutations):
    means = []
    for i in range(0,number_of_permutations):
        means.append(permutation_mean(x,y))
    means.sort()
    hmean = np.mean(means)
    hstd = np.std(means)
    pdf = stats.norm.pdf(means, hmean, hstd)
    Z_score = (means - np.mean(means))/np.std(means)
    normal_distribution = pd.DataFrame({'means':means,'Zscore':Z_score,'PDF':pdf})
    return normal_distribution

def get_guassian_values(x,series):
    one_over_std = 1/(np.std(series)*np.sqrt(2*3.14159))
    factor_numerator = -1*(x - np.mean(series))**2
    factor_denomenator = 2*(np.std(series)**2)
    exponential_factor = factor_numerator/factor_denomenator
    return one_over_std*np.exp(exponential_factor)

def Hypothesis_Test(data,column,number_of_permutations):
    cv,ncv = seperate_dataframe(data,column)
    normal_distribution = build_normal_distribution(cv,ncv,number_of_permutations)
    actual_mean_difference = np.mean(cv) - np.mean(ncv)
    Z_test = (actual_mean_difference-np.mean(normal_distribution['means']))/np.std(normal_distribution['means'])
    Guassian_of_actual = get_guassian_values(actual_mean_difference,normal_distribution['means'])
    if Z_test > 0:
        critical_region = normal_distribution[normal_distribution['Zscore']>Z_test][['Zscore','PDF']]
    elif Z_test<0:
        critical_region = normal_distribution[normal_distribution['Zscore']<Z_test][['Zscore','PDF']]
    else:
        critical_region = normal_distribution[['Zscore','PDF']]
    try:
        p_value = auc(critical_region['Zscore'],critical_region['PDF'])
    except ValueError:
        p_value = 0
    p_value=round(p_value,6)
    if (np.abs(Z_test)>2.58) and (p_value<0.005):
        if p_value==0:
            string= str(column)+'\n'+"Reject Null Hypothesis that both converters and non_converters \n have the same distribution, with p < 0.005 and Z score: "+str(Z_test)
            #print(string)
            return string
        else:
            string = str(column) + "Reject Null Hypothesis that both converters and non_converters \n have the same distribution, with p < "+str(p_value)+' and Z score: '+str(Z_test)
            #print(string)
            return string
    else:
        string = str(column)+" Fail to reject Null Hypothesis"
        #print(string)
        return string
    
tests_on_viewing1 = {}
for feature in data2.drop('voted_for_republican',axis=1).columns:
    tests_on_viewing1[feature] = [Hypothesis_Test(data2,feature,10000)]
    
tests = pd.DataFrame(tests_on_viewing1).transpose().reset_index().rename(columns={'index':'Feature',0:'Test'})
def pass_fail(x):
    if 'Fail' in x:
        return 'PASS'
    else:
        return "REJECT NULL"
tests['result'] = tests['Test'].apply(lambda x:pass_fail(x))
tests['Count'] = tests['result'].apply(lambda x: 1 if 'REJECT' in x else 0)
percent_of_rejecting_null_hypothesis_test = 100*tests['Count'].sum()/len(tests)
print("% of features we reject null hypothesis: ", percent_of_rejecting_null_hypothesis_test)
tests.to_csv('Interactions_features_test_voters.csv')
for results in tests[tests['Count']==1]['Test']:
    print(results)
    print('\n')

% of features we reject null hypothesis:  5.491990846681922
age
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -3.756602425322815


education_doctorate
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 4.157468402721064


education_some_college
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -4.241508383192772


freq_voter education_some_college
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -3.5159370964371144


freq_voter party_D
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -5.568568023840441


freq_voter party_R
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 5.506586197416972


home_owner_H education_doctorate
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 4.4652958369579485


party_D
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -6.408331137615989


party_D education_some_college
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -4.236074509571358


party_D ethnic_whiteReject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.002708 and Z score: -3.456279726717153


party_D renters_YReject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.003657 and Z score: -3.44136368976872


party_R
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 5.851857801098726


party_R education_doctorate
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 4.209088643029793


party_R home_owner_H
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 5.772661739194654


party_R ismarried_Y
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 3.385710930632193


party_R sex_MReject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.004259 and Z score: 3.7149196252186196


voted_03_05_2013 education_bachelors
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -4.20475348895292


voted_03_05_2013 party_D
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -6.148753997454935


voted_03_05_2013 party_R
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 5.133910416626873


voted_05_21_2013 education_doctorate
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 3.4703081720460514


voted_05_21_2013 party_D
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -5.0714719802855095


voted_05_21_2013 party_R
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 4.799105776291061


voted_06_07_2016 party_D
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: -5.115993932528102


voted_06_07_2016 party_R
Reject Null Hypothesis that both converters and non_converters
 have the same distribution, with p < 0.005 and Z score: 5.597015680587811

In [22]:
data_significant = data2[['voted_for_republican']+list(tests[tests['Count']==1]['Feature'])]
feature_measures1_a = {}
feature_measures1_na = {}
for feature in data_significant.drop('voted_for_republican',axis=1).columns:
    if len(data_significant[feature].unique())==2:
        feature_measures1_a[feature] = [data_significant[data_significant['voted_for_republican']==1][feature].sum()]
        feature_measures1_na[feature] = [data_significant[data_significant['voted_for_republican']==0][feature].sum()]

s1 = pd.DataFrame(feature_measures1_a).transpose().reset_index().rename(columns={'index':'Feature',0:'For_A_Count'})
s2 = pd.DataFrame(feature_measures1_na).transpose().reset_index().rename(columns={'index':'Feature',0:'Against_A_Count'})
signal = pd.merge(s1,s2,how='inner',on='Feature')
signal['Difference'] = signal[['For_A_Count','Against_A_Count']].apply(lambda row: row['For_A_Count'] - row['Against_A_Count'],axis=1)
signal['Favoring']=signal['Difference'].apply(lambda x: 'For' if x>0 else 'Against')
signal=signal[['Feature','Favoring','For_A_Count','Against_A_Count','Difference']]
signal.sort_values(by='Favoring',ascending=True,inplace=True)
signal

,Feature,Favoring,For_A_Count,Against_A_Count,Difference
1,education_some_college,Against,131.0,209.0,-78.0
2,freq_voter education_some_college,Against,102.0,162.0,-60.0
3,freq_voter party_D,Against,344.0,476.0,-132.0
19,voted_05_21_2013 party_D,Against,233.0,346.0,-113.0
6,party_D,Against,454.0,602.0,-148.0
7,party_D education_some_college,Against,131.0,209.0,-78.0
8,party_D ethnic_white,Against,189.0,263.0,-74.0
9,party_D renters_Y,Against,193.0,267.0,-74.0
21,voted_06_07_2016 party_D,Against,394.0,519.0,-125.0
16,voted_03_05_2013 party_D,Against,221.0,353.0,-132.0
15,voted_03_05_2013 education_bachelors,Against,100.0,170.0,-70.0
0,education_doctorate,For,61.0,25.0,36.0
20,voted_05_21_2013 party_R,For,110.0,55.0,55.0
18,voted_05_21_2013 education_doctorate,For,39.0,15.0,24.0
17,voted_03_05_2013 party_R,For,128.0,65.0,63.0
11,party_R education_doctorate,For,61.0,25.0,36.0
13,party_R ismarried_Y,For,54.0,26.0,28.0
12,party_R home_owner_H,For,127.0,57.0,70.0
10,party_R,For,179.0,97.0,82.0
5,home_owner_H education_doctorate,For,52.0,17.0,35.0
4,freq_voter party_R,For,161.0,87.0,74.0
14,party_R sex_M,For,93.0,53.0,40.0
22,voted_06_07_2016 party_R,For,145.0,74.0,71.0